import INameToValueMap from "../shared/INameToValueMap";

const phonemes:INameToValueMap = {
    "AAE":{
        "graphemes":[
            "a",
            "au"
        ],
    },
    "AHH":{
        "graphemes":[
            "a",
            "o",
            "eau"
        ],
    },
    "AWW":{
        "graphemes":[
            "a",
            "o",
            "au",
            "aw",
            "oa",
            "augh",
            "ough"
        ],
    },
    "AYE":{
        "graphemes":[
            "a",
            "e",
            "é",
            "ai",
            "ay",
            "ea",
            "ei",
            "eigh",
            "ey",
            "aigh"
        ],
    },
    "EHH":{
        "graphemes":[
            "a",
            "e",
            "ea",
            "ie"
        ],
    },
    "IHH":{
        "graphemes":[
            "a",
            "e",
            "i",
            "y",
            "ai",
            "ei",
            "ui"
        ],
    },
    "UHH":{
        "graphemes":[
            "a",
            "e",
            "é",
            "i",
            "o",
            "u",
            "y",
            "au",
            "ia",
            "io",
            "iou",
            "oo",
            "ou"
        ],
    },
    "EEE":{
        "graphemes":[
            "e",
            "é",
            "i",
            "y",
            "ea",
            "ee",
            "ei",
            "ey",
            "ie"
        ],
    },
    "SIL":{
        "graphemes":[
            "e",
            "h",
            "l",
            "s",
            "t",
            "x",
            "?i",
            "1",
            "2",
            "3",
            "4",
            "'",
            "-",
            "_"
        ],
    },
    "EYE":{
        "graphemes":[
            "i",
            "y",
            "ei",
            "eigh",
            "ie",
            "igh",
            "uy"
        ],
    },
    "YY":{
        "graphemes":[
            "i",
            "y"
        ],
    },
    "OOO":{
        "graphemes":[
            "o",
            "u",
            "eu",
            "ew",
            "oo",
            "ou",
            "ue",
            "ui"
        ],
    },
    "OWE":{
        "graphemes":[
            "o",
            "oa",
            "oe",
            "ou",
            "ow",
            "eau",
            "ough"
        ],
    },
    "UUH":{
        "graphemes":[
            "o",
            "u",
            "oo"
        ],
    },
    "YOU":{
        "graphemes":[
            "u",
            "eu",
            "ew",
            "iew",
            "ue",
            "eau"
        ],
    },
    "BB":{
        "graphemes":[
            "b",
            "bb"
        ],
    },
    "KK":{
        "graphemes":[
            "c",
            "k",
            "q",
            "ch",
            "ck",
            "cc",
            "kk",
            "qué",
            "que"
        ],
    },
    "SH":{
        "graphemes":[
            "c",
            "s",
            "t",
            "ch",
            "ci",
            "sh",
            "si",
            "ti"
        ],
    },
    "SS":{
        "graphemes":[
            "c",
            "s",
            "t",
            "z",
            "ss",
            "ps",
            "sc",
            "st"
        ],
    },
    "DD":{
        "graphemes":[
            "d",
            "dd"
        ],
    },
    "JJ":{
        "graphemes":[
            "d",
            "g",
            "j",
            "dg",
            "dge",
            "gg"
        ],
    },
    "TT":{
        "graphemes":[
            "d",
            "t",
            "th",
            "tt",
            "bt"
        ],
    },
    "FF":{
        "graphemes":[
            "f",
            "ph",
            "ff",
            "lf"
        ],
    },
    "GG":{
        "graphemes":[
            "g",
            "gg",
            "gh",
            "gu",
            "gue"
        ],
    },
    "ZH":{
        "graphemes":[
            "g",
            "s",
            "t"
        ],
    },
    "HHH":{
        "graphemes":[
            "h",
            "wh"
        ],
    },
    "LL":{
        "graphemes":[
            "l",
            "ll"
        ],
    },
    "MM":{
        "graphemes":[
            "m",
            "mm",
            "mb",
            "mn"
        ],
    },
    "NG":{
        "graphemes":[
            "n"
        ],
    },
    "NN":{
        "graphemes":[
            "n",
            "nn",
            "gn",
            "kn",
            "pn"
        ],
    },
    "PP":{
        "graphemes":[
            "p",
            "pp"
        ],
    },
    "KKWW":{
        "graphemes":[
            "qu"
        ],
    },
    "RR":{
        "graphemes":[
            "r",
            "rr",
            "rh",
            "wr"
        ],
    },
    "ZZ":{
        "graphemes":[
            "s",
            "x",
            "z",
            "ss",
            "zz"
        ],
    },
    "CH":{
        "graphemes":[
            "t",
            "ch",
            "tch"
        ],
    },
    "WW":{
        "graphemes":[
            "u",
            "w",
            "wh",
            "ww"
        ],
    },
    "VV":{
        "graphemes":[
            "v"
        ],
    },
    "GZ":{
        "graphemes":[
            "x"
        ],
    },
    "XX":{
        "graphemes":[
            "x"
        ],
    },
    "AYERR":{
        "graphemes":[
            "air",
            "ar",
            "arr",
            "ear",
            "eir",
            "er",
            "err"
        ],
    },
    "ARR":{
        "graphemes":[
            "ar",
            "arr",
            "ear",
            "or",
            "orr"
        ],
    },
    "IRR":{
        "graphemes":[
            "ar",
            "ear",
            "er",
            "err",
            "ir",
            "or",
            "orr",
            "our",
            "ur",
            "ure",
            "urr",
            "yr",
            "?r"
        ],
    },
    "ORR":{
        "graphemes":[
            "ar",
            "arr",
            "oar",
            "oor",
            "or",
            "ore",
            "orr",
            "our"
        ],
    },
    "EEERR":{
        "graphemes":[
            "ear",
            "eer",
            "er",
            "ier",
            "ir",
            "irr",
            "yr"
        ],
    },
    "OWWRR":{
        "graphemes":[
            "our"
        ],
    },
    "YER":{
        "graphemes":[
            "ur",
            "ure"
        ],
    },
    "WWORR":{
        "graphemes":[
            "war"
        ],
    },
    "WWIRR":{
        "graphemes":[
            "wor"
        ],
    },
    "DH":{
        "graphemes":[
            "th"
        ],
    },
    "TH":{
        "graphemes":[
            "th"
        ],
    },
    "OIY":{
        "graphemes":[
            "oi",
            "oy"
        ],
    },
    "OWW":{
        "graphemes":[
            "ou",
            "ow"
        ],
    },
    "IHHSSSIL":{
        "graphemes":[
            "ace",
            "ice"
        ],
    },
    "IHHJJSIL":{
        "graphemes":[
            "age"
        ],
    },
    "AWWLLKK":{
        "graphemes":[
            "alk"
        ],
    },
    "AWWLL":{
        "graphemes":[
            "all"
        ],
    },
    "AWWLLTT":{
        "graphemes":[
            "alt"
        ],
    },
    "AAEMM":{
        "graphemes":[
            "am"
        ],
    },
    "AAENN":{
        "graphemes":[
            "an"
        ],
    },
    "AAENGGG":{
        "graphemes":[
            "ang"
        ],
    },
    "AAENGKK":{
        "graphemes":[
            "ank"
        ],
    },
    "IHHTTSIL":{
        "graphemes":[
            "ate",
            "ite"
        ],
    },
    "EYELLDD":{
        "graphemes":[
            "ild"
        ],
    },
    "IHHLLSIL":{
        "graphemes":[
            "ile"
        ],
    },
    "EYENNDD":{
        "graphemes":[
            "ind"
        ],
    },
    "IHHNNSIL":{
        "graphemes":[
            "ine"
        ],
    },
    "IHHNGGG":{
        "graphemes":[
            "ing"
        ],
    },
    "IHHNGKK":{
        "graphemes":[
            "ink"
        ],
    },
    "IHHVVSIL":{
        "graphemes":[
            "ive"
        ],
    },
    "OWELLDD":{
        "graphemes":[
            "old"
        ],
    },
    "OWELL":{
        "graphemes":[
            "oll"
        ],
    },
    "OWELLKK":{
        "graphemes":[
            "olk"
        ],
    },
    "OWELLTT":{
        "graphemes":[
            "olt"
        ],
    },
    "AWWNGGG":{
        "graphemes":[
            "ong"
        ],
    },
    "AHHNGKK":{
        "graphemes":[
            "onk"
        ],
    },
    "OWESSTT":{
        "graphemes":[
            "ost"
        ],
    },
    "SHUHHNN":{
        "graphemes":[
            "sion",
            "tion"
        ],
    },
    "ZHUHHNN":{
        "graphemes":[
            "sion",
            "tion"
        ],
    },
    "SHIRR":{
        "graphemes":[
            "sure"
        ],
    },
    "ZHIRR":{
        "graphemes":[
            "sure"
        ],
    },
    "CHUHHNN":{
        "graphemes":[
            "tion"
        ],
    },
    "CHIRR":{
        "graphemes":[
            "ture"
        ],
    },
    "UHHNGGG":{
        "graphemes":[
            "ung"
        ],
    },
    "UHHNGKK":{
        "graphemes":[
            "unk"
        ],
    },
    "AAEFF":{
        "graphemes":[
            "augh"
        ],
    },
    "UHHFF":{
        "graphemes":[
            "ough"
        ],
    },
    "SSLLSIL":{
        "graphemes":[
            "stle"
        ],
    },
    "CHOOO":{
        "graphemes":[
            "tu"
        ],
    },
    "WWAHH":{
        "graphemes":[
            "wa"
        ],
    },
    "KKAYE":{
        "graphemes":[
            "qué"
        ],
    },
    "NGGG":{
        "graphemes":[
            "ng"
        ],
    },
    "NGKK":{
        "graphemes":[
            "nk"
        ],
    }
};

export {phonemes};
